LUCCA-Capstone/LUCCA

- README.md
Build status is now visible on
the git repo README
> add travis-ci build status

- public/stylesheets/UserSignIn.css
- views/UserSignIn.html
Here is my final code after the update, please review it.
> Bishoy hanna/user sign in page

- .travis.yml
- package-lock.json
- package.json
- test/testApp.js
> Mocha Chai and Travis

- routes/index.js
- views/error.pug
- views/index.pug
- views/layout.pug
1) I delete the bugs files from the view folder.
2) I made few changes in index.js file
please review my code
> Bishoy hanna remove bugs from project

- package-lock.json
- views/_layout.njk
- views/adminLogin.njk
added _layout.njk base file and inherited it in adminLogin.njk, re-defining blocks where appropriate.
> Added _layout.njk and inheritted it in adminLogin.njk

- test/bin/station-sim.py3
This adds the ability to use this script without SSL certs at either client or server side.
Additionally, fix the expected response body in the script to match the HTTP protocol standard
> Add a --no-ssl option to station mock

- .travis.yml
- test/test-pages.js
Let's all have a working Travis! Yay!
> Andy add test errors

- .travis.yml
- app.js
- routes/api.js
Handles access request from users
> api: handles access request

- package-lock.json
- public/stylesheets/navbar.css
- routes/index.js
- views/HomePage.njk
Modified my HomePage.html file using nunchuck blocks inherited from layout file and modified css file to make it consistent with Mike's Admin Sign in page.
> Modify HomePage.html using nunchuck blocks

- routes/index.js
- views/badgein.njk
I am done with the function of badge in page, so when anyone press the submit button the badge in number is passed to the valideUser(). Can You review my code ?
> Bishoy hanna add function tobadgein page

- database/controllers/dbm.js
- test/db_tests/db_test.js
basic unit tests for getStations
> adding getStations

- database/controllers/dbm.js
- package.json
- test/db_tests/db_test.js
Tried using the async/awaits method...I think I used it properly.  Let me know what you think.
> getPrivileges method using async/awaits

- database/migrations/20180131235103-create-privileges.js
- database/models/privileges.js
- database/seeders/20180201195559-add-privileges.js
--Removed "trained" attribute field in both model/migration, as it is no longer needed.
--Updated add-privileges seeder file to no longer set the "trained" field.
> Updated privileges model/migration

- database/migrations/20180131234858-create-user.js
- database/models/user.js
- test/db_tests/db_test.js
Made the email field unique so no two users can share the same email.
> Updated the user models/migrations

- public/stylesheets/userManagement.css
- routes/index.js
- views/userManagement.njk
User management page with list of users query from DB done.
Working on Searching a specific user (search bar) and Edit(user/station) - what does it do btw?
> Add User management page

- database/controllers/dbm.js
- test/db_tests/db_test.js
removePrivileges tests required grantPrivileges so I decided to just add everything to one branch. 
Note - all test pass except I've been having issue with the deleteEvent test occasionally exceeding a mocha/chai timeout of 2000ms.
--Edit:  The deleteEvent test seems to be passing now
> grantPrivileges + removePrivileges + new Tests

- public/stylesheets/badgeinSuccess.css
- routes/index.js
- test/test-pages.js
- views/badgeinSuccess.njk
I am done with the Badge In success, so when the badge of the user is in the database, the user will be directed to this page, can u revise my code?
> add badge in success page

- app.js
- package.json
- passport/login.js
- passport/register.js
- passport/reset.js
- routes/index.js
- routes/users.js
- test/test-pages.js
- views/adminLogin.njk
- views/adminRegister.njk
- views/adminReset.njk
- An admin can now register another user by making them enter an email and
password of their choosing
- An admin can now log into the system and be authenticated
- An admin can now reset their password
- Routes can be protected allowing only admin access
I did some manual testing, let me know if you see something out of the ordinary or anything that seems broken.
> Adds passport authentication

- package-lock.json
- public/stylesheets/adminLogin.css
- public/stylesheets/badgein.css
- public/stylesheets/badgeinSuccess.css
- public/stylesheets/registration.css
- routes/index.js
- test/test-pages.js
- views/_layout.njk
- views/adminLogin.njk
- views/badgein.njk
- views/stationManagement.njk
added stationManagement tests and removed extra padding above navbar
updating package-lock file for passport module
each row now has update and delete button and checkbox
commenting out sort function until database is avail. to Travis
> added station management with get and post routes

- routes/index.js
Can You take a look at my code and tell me your opinion ?
> adding routes for the userManagement page

- database/controllers/dbm.js
- routes/index.js
- views/_layout.njk
Framework in place for message passing between route to route and between route to DOM. I'll try to add a few notes to the code in case you have questions... but feel free to checkout my branch and try it out. 
I think the best way to see the messages in action is to load the stationManagement page and make use of the "Update" button to "register" and "unregister" stations. This gives you the ability to put them back to their original status when you're done so DB tests won't fail. Try to avoid the "Delete" button.
> adding framework for alerts. Now used by stationManagement routes

- lib/station-log.js
This module is used to store station information,
and modify station information.
> station log module: log station information

- routes/index.js
HI Daniel, can u take a look at my code after I resolved the conflict I wanna make sure everything is fine after I rebase from the master
> update the routes of the BadgeIn and userManagement page

- lib/station-log.js
- routes/api.js
Sets a station's status to disabled in the cached station object.
> Created an api local reset

- lib/station-log.js
- routes/api.js
My tests were run on postman using localhost:3001.  I believe I covered all my basis but please let me know if you catch anything not working as it should.
Note - I'll be removing the console.logs before I merge.  I used them for testing and figured I'd leave them in to help others test.
> Created an API to get the last known status for a station

- lib/station-log.js
- routes/api.js
Reverts LUCCA-Capstone/LUCCA#63
> Revert "Created an API to get the last known status for a station"

- lib/station-log.js
- routes/api.js
Same working/tested/reviewed code from my first last-state PR but this one will avoid the odd merging issues I was having with git replacing all my last-state code with the the local-reset code.
> last-state api call

- routes/index.js
>  Create Log Event For User Badge In Lab

- routes/index.js
- views/userManagement.njk
- views/userManagementBadge.njk
+ Done with the User Management Page (see attachment below)
+ When the user click on the button (Validate/Delete User) or (Revoke/Grant Access station), it will go to Bishoy's routes correspondingly (I did not test his routes).
> Finished UI of User Management (User+Station tables)

- routes/index.js
- test/test-pages.js
- views/userManagementBadge.njk
I added an option  when the user is already validated; to  promote a user to be manager and demote the manager to be user.
Please, check the code.
> Adding button to promote or demote the user

- api_app.js
- lib/cache.js
- lib/station-log.js
- routes/api.js
- test/api-test.js
Adds user-access along with caching module and test for user-access api
> api: user-access

- views/userManagement.njk
- views/userManagementBadge.njk
I updated the search bar for the userManagement page, so the admin can search by badge or name.
Please take a look at my code.
> Make the User Search More Flexible

- routes/index.js
- views/registration.njk
- added user registration form validation for values and sanitation
- form will flash errors if any of the fields are wrong or if there are any other issues
- it will check if a badge or email are already in use and will error out and let user know
- if the data is good but there is still an issue during createUser phase, it will display a validation error
- upon submission, if errors are encountered, the valid form fields will be preserved and the ones that are causing issues will be wiped out, this makes it a better user experience since the person will not need to retype information that is already considered valid by the system
> Added user registration form validation

- database/controllers/dbm.js
- routes/index.js
- Added DB function given station ID it will return all user rows that have privileges to use that station
- Added route handler that you can call to retrieve the users and for testing
- Other unrelated formatting fixes
> Retrieve privileged users

- database/migrations/20180131234858-create-user.js
- database/models/user.js
- database/seeders/20180301224915-add-admin.js
Please refer to the instruction at the bottom of the Database Setup file in our shared google drive for setup, testing, and connection on this PR.
Note: Do not confuse this setup with my other PR request: Bryan_DBConfig_To_LuccaConfig  which is also at the bottom of the page.
> Updated user migration/model file + created admin seeder file

- routes/index.js
- views/_layout.njk
- Added badge in validaton, that checks to make sure badge entered in a numeric string
- Added a `req.flash('fade_out', 'millis_here');` call which you can use after flashing your messages to instruct them to fade out after some number of milliseconds on the next page. Make sure both args are strings being passed in
- Removed some console.log calls as they were outputting a lot of information spam to the console. We should probably at some point go through those and remove anything that may be outputting sensitive information
> Added badge in validation and modified message flashing

- database/controllers/dbm.js
- test/db_test.js
This function will return the user's information if the user has a loggedIn value of true.  Otherwise it will return false.
Let me know what you think as I may still not be 100% on what you are expecting from this function.
--Note: Testing was done on epl3
> getLoggedIn DB function

- routes/api.js
adds logging for events when a user logs on and
off to a machine
> api user-access: Log on and off machine

- public/javascripts/updateUserInfo.js
- routes/index.js
- views/_layout.njk
- views/userManagementBadge.njk
- You are now able to update a select number of fields for a user through the management UI
- You can update first and last name, email, phone number, emergency contact name, relation, and phone number
- You are not able to modify signatures for liability purposes
- Added a button at the button that can be clicked to submit modified fields. Button will not submit unless one of the fields has been modified.
- Added new post route `'/userManagement/updateUserInfo/:badge'`, route will also check fields to make sure they are valid.
- Appropriate error and success messages should be displayed
> Added ability to update various user info fields from user management UI

- database/controllers/dbm.js
- database/migrations/20180131235149-create-log.js
- database/models/log.js
- routes/api.js
- routes/index.js
- test/db_test.js
This branch will be squashed before merge as per Daniel's suggestion
> Update logging schema to include entity column

- public/javascripts/userManagement.js
- public/stylesheets/style.css
- routes/index.js
- views/_layout.njk
- views/userManagement.njk
- Updated userManagement view to include two text inputs, two drop-down selectors, a dateRangePicker, and a "search" and "clear" button. All inputs play nicely with each other and retain the previous text to support sequential searches - so an admin can drill down into the results and whittle away users they're not interested in. Can now search by:
1. Badge number
2. Name (caps insensitive; allows partial match)
3. Status {User, Manager, Admin}
4. Registration date range
5. Permissions (users with access to a particular station) [I just piggy-backed on the work Bishoy did]
- Updated post route for userManagement in index to find (and return) the intersection of the various inputs requested (if and when they exist).
- Some other little things.
> Mike o user search by date and status

- routes/index.js
- views/userManagementBadge.njk
Adding button to demote Admin to manager in the user page.
There is minor error, when admin 1 logged in by his email, demoted admin 2 to manager and trying to delete admin 2 after that immediately  the page crush. However, when admin 1 or admin 2 logged out the page, and admin 1 logged in by his email, and  try to delete admin 2(manger now) it works. The whole point depends on that admin 1 must log out to delete admin 2. 
Run the program and you will see what I am saying.
> Bishoy add button to demote admin

- routes/index.js
- views/stationManagement.njk
Finished the ticket "Add a collumn that shows who is currently using a particular station." and tested with postman - see the attachment below.
> Added who is currently using a particular station

- database/controllers/dbm.js
- public/javascripts/userManagement.js
- routes/index.js
- views/eventsLog.njk
- views/userManagementBadge.njk
I started from my other branch after I did my original pull request, so this includes those changes. Also: 
- updated dropdown in eventsLog.njk and function in route handler to match final decided set of events.
- Added new "entity" column to events page.
> Mike o station management filter update

- passport/login.js
- passport/register.js
- passport/reset.js
- routes/index.js
- views/adminReset.njk
- Please let me know if I missed anything or should add anything to make the logging clearer
> Added DB logging of critical events that happen as result of frontend UI interaction

- passport/login.js
> explicit null check for user password in passport login
